version: '3.2'
services:

  gitlab:
    image: gitlab/gitlab-ce:16.4.0-ce.0
    hostname: 127.0.0.1
    container_name: gitlab
    restart: always
    volumes:
      - /home/gcobt02/gitlab/config:/etc/gitlab
      - /home/gcobt02/gitlab/logs:/var/log/gitlab
      - /home/gcobt02/gitlab/data:/var/opt/gitlab
    ports:
      - '80:80'
      - '443:443'
      - '10022:22'
    networks:
      - devel-net

networks:
  devel-net:
