version: '2'

services:
  redis:
    restart: always
    image: redis:6.2.7
    command:
    - --loglevel warning
    volumes:
    - /home/gitlab/redis:/var/lib/redis

  postgresql:
    restart: always
    image: sameersbn/postgresql:12-20200524
    volumes:
    - /home/gitlab/postgresql:/var/lib/postgresql
    environment:
    - DB_USER=gitlab
    - DB_PASS=
    - DB_NAME=db_gitlab
    - DB_EXTENSION=pg_trgm

  gitlab:
    restart: always
    image: sameersbn/gitlab:15.3.5
    depends_on:
    - redis
    - postgresql
    ports:
    - "80:80"
    - "10022:22"
    volumes:
    - /home/gitlab/data:/home/git/data
    - /home/gitlab/logs:/var/log/gitlab
    environment:
    - DEBUG=false
    - GITLAB_HTTPS=false
    - SSL_SELF_SIGNED=true
    - TZ=Asia/Taipei
    - GITLAB_TIMEZONE=Taipei
    - GITLAB_HOST=
    - GITLAB_PORT=80
    - GITLAB_SSH_PORT=10022
    - GITLAB_SECRETS_DB_KEY_BASE=
    - GITLAB_SECRETS_SECRET_KEY_BASE=
    - GITLAB_SECRETS_OTP_KEY_BASE=
    - DB_ADAPTER=postgresql
    - DB_HOST=postgresql
    - DB_PORT=5432
    - DB_USER=gitlab
    - DB_PASS=
    - DB_NAME=db_gitlab
    - REDIS_HOST=redis
    - REDIS_PORT=6379
networks:
  default:
    external:
      name: gitlab

