version: "3"

services:
  jenkins:
    image: jenkins/jenkins:2.263.3-lts
    container_name: jenkins-compose
    restart: always
    ports:
      - "80:8080"
      - "50000:50000"
    volumes:
      - "/home/jenkins:/var/jenkins_home"
    environment:
      - JAVA_OPTS=-Duser.timezone=Asia/Taipei
      - JAVA_OPTS=-Dfile.encoding=UTF-8
      - JAVA_OPTS=-Xmx4096m
