version: "3"

services:
  jenkins:
    image: jenkins/jenkins:2.387.2-jdk17
    container_name: jenkins-compose
    restart: always
    deploy:
      resources:
        limits:
          memory: 4096m
        reservations:
          memory: 2048m
    ports:
      - "80:8080"
      - "50000:50000"
    volumes:
      - "/home/jenkins:/var/jenkins_home"
    environment:
      - TZ=Asia/Taipei
      - JAVA_OPTS=-Dfile.encoding=UTF-8
      - JAVA_OPTS=-Xmx4096m
    extra_hosts:
     - "hostname:IP"
     
